#!/usr/bin/env bash
# git-dr-mirror installer.
#
#   ./install.sh              install (or update) everything
#   ./install.sh --uninstall  remove the systemd units; keep code, .env, mirrors
#
# What install does:
#   1. Creates .venv and installs the tool (uv if available, else python3+pip).
#   2. Creates .env from .env.example if missing (never overwrites).
#   3. Installs systemd *user* units (Linux only; prints a cron alternative otherwise).
#   4. Offers to enable the timer.
#
# Works the same on a laptop and on a VPS. Runs entirely as your user; no root.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_NAME="git-dr-mirror"

# --- output helpers ---------------------------------------------------------

if [ -t 1 ]; then
    _bold=$'\033[1m' _green=$'\033[32m' _yellow=$'\033[33m' _red=$'\033[31m' _reset=$'\033[0m'
else
    _bold='' _green='' _yellow='' _red='' _reset=''
fi

info() { printf '%s\n' "${_green}==>${_reset} ${_bold}$*${_reset}"; }
warn() { printf '%s\n' "${_yellow}warning:${_reset} $*" >&2; }
die()  { printf '%s\n' "${_red}error:${_reset} $*" >&2; exit 1; }

# --- uninstall --------------------------------------------------------------

uninstall() {
    info "Uninstalling systemd units"
    systemctl --user disable --now "$UNIT_NAME.timer" 2>/dev/null || true
    rm -f "$UNIT_DIR/$UNIT_NAME.service" "$UNIT_DIR/$UNIT_NAME.timer"
    rm -rf "$UNIT_DIR/$UNIT_NAME.service.d" "$UNIT_DIR/$UNIT_NAME.timer.d"
    systemctl --user daemon-reload 2>/dev/null || true
    info "Done. The clone, .venv, .env, and your mirrors were left untouched."
    exit 0
}

case "${1:-}" in
    --uninstall) uninstall ;;
    "") ;;
    *) die "unknown option '$1' (usage: ./install.sh [--uninstall])" ;;
esac

# --- prerequisites ----------------------------------------------------------

command -v git >/dev/null 2>&1 \
    || die "git is not installed: install it with your package manager and rerun."

have_systemd=true
if ! systemctl --user show-environment >/dev/null 2>&1; then
    have_systemd=false
    warn "no systemd user session found: the venv and .env will be set up,"
    warn "but you'll need to schedule runs yourself (a cron line is printed at the end)."
fi

# --- python environment (uv preferred, pip fallback) ------------------------

cd "$REPO_DIR"

if command -v uv >/dev/null 2>&1; then
    info "Installing with uv"
    uv sync || die "'uv sync' failed: see the output above."
else
    info "uv not found. Falling back to python3 + venv + pip"
    command -v python3 >/dev/null 2>&1 \
        || die "python3 is not installed. Install Python 3.9+ or uv (https://docs.astral.sh/uv/)."
    python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)' \
        || die "Python 3.9+ required, found $(python3 --version 2>&1). Install a newer Python or uv (https://docs.astral.sh/uv/ - uv can provision Python for you)."
    if [ ! -x .venv/bin/pip ]; then
        python3 -m venv .venv \
            || die "could not create a virtualenv. On Debian/Ubuntu: sudo apt install python3-venv"
    fi
    .venv/bin/pip install --quiet --editable . \
        || die "'pip install' failed: see the output above."
fi

.venv/bin/git-dr-mirror --version >/dev/null \
    || die "installation sanity check failed: .venv/bin/git-dr-mirror does not run."
info "Installed $(.venv/bin/git-dr-mirror --version)"

# --- configuration ----------------------------------------------------------

env_ready=true
if [ ! -f .env ]; then
    cp .env.example .env
    chmod 600 .env
    info "Created .env (mode 600): fill in GITHUB_TOKEN, GITLAB_TOKEN, GITLAB_GROUP"
fi
# "Filled in" = every required key has a non-empty value.
for key in GITHUB_TOKEN GITLAB_TOKEN GITLAB_GROUP; do
    grep -Eq "^${key}=.+" .env || env_ready=false
done
if ! $env_ready; then
    warn ".env is missing required values (GITHUB_TOKEN, GITLAB_TOKEN, GITLAB_GROUP)."
fi

# --- systemd units ----------------------------------------------------------

if $have_systemd; then
    info "Installing systemd user units in $UNIT_DIR"
    mkdir -p "$UNIT_DIR"

    cat > "$UNIT_DIR/$UNIT_NAME.service" <<EOF
# Generated by $REPO_DIR/install.sh: rerun it after moving the clone.
[Unit]
Description=GitHub -> GitLab disaster-recovery mirror
# Don't fire while the network is still coming up after boot/resume.
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
# The tool reads its configuration from the .env file in this directory.
WorkingDirectory=$REPO_DIR
ExecStart=$REPO_DIR/.venv/bin/git-dr-mirror
# A backup should never make the machine you're working on feel slow.
Nice=10
IOSchedulingClass=idle

[Install]
WantedBy=default.target
EOF

    cat > "$UNIT_DIR/$UNIT_NAME.timer" <<EOF
# Generated by $REPO_DIR/install.sh: don't edit this file directly, it is
# overwritten on reinstall. To change the schedule, use a drop-in override
# (survives reinstalls):
#
#   systemctl --user edit $UNIT_NAME.timer
#
# and enter, e.g. for daily at 03:17:
#
#   [Timer]
#   OnCalendar=
#   OnCalendar=*-*-* 03:17:00
#
# (The empty OnCalendar= line clears the default below before setting yours.)
[Unit]
Description=Run git-dr-mirror every 6 hours

[Timer]
# Every 6 hours at :17 past the hour.
OnCalendar=00/6:17:00
# Catch up on a run missed while powered off / asleep.
Persistent=true
# Spread the start a little so boot isn't a thundering herd.
RandomizedDelaySec=5m
Unit=$UNIT_NAME.service

[Install]
WantedBy=timers.target
EOF

    systemctl --user daemon-reload

    # --- enable the timer ---------------------------------------------------

    timer_enabled=false
    if systemctl --user is-enabled --quiet "$UNIT_NAME.timer" 2>/dev/null; then
        timer_enabled=true
        info "Timer already enabled."
    elif ! $env_ready; then
        : # pointless to enable a timer whose runs can only fail
    elif [ -t 0 ]; then
        printf 'Enable the 6-hour backup timer now? [Y/n] '
        read -r answer
        case "$answer" in
            [Nn]*) ;;
            *) systemctl --user enable --now "$UNIT_NAME.timer"; timer_enabled=true ;;
        esac
    fi

    # Lingering: without it, user timers stop when you log out (VPS!).
    if [ "$(loginctl show-user "$USER" --property=Linger --value 2>/dev/null)" = "no" ]; then
        warn "to keep backups running while you're logged out (e.g. on a VPS), run:"
        warn "    loginctl enable-linger $USER"
    fi
fi

# --- next steps / wizard launch ---------------------------------------------

echo
if ! $env_ready && [ -t 0 ]; then
    info "Launching the interactive setup wizard..."
    "$REPO_DIR/.venv/bin/git-dr-mirror" setup
else
    info "Install complete. Next steps:"
    if ! $env_ready; then
        echo "  1. Run the setup wizard:       $REPO_DIR/.venv/bin/git-dr-mirror setup"
        echo "     (or fill in tokens manually: \$EDITOR $REPO_DIR/.env)"
    fi
    echo "  Preview without changes:       $REPO_DIR/.venv/bin/git-dr-mirror --dry-run"
    echo "  Test with a single repo:       $REPO_DIR/.venv/bin/git-dr-mirror --repo some-small-repo"
    if $have_systemd; then
        if ! $timer_enabled; then
            echo "  Enable the schedule:           systemctl --user enable --now $UNIT_NAME.timer"
        fi
        echo "  Check the schedule:            systemctl --user list-timers $UNIT_NAME.timer"
        echo "  Run a backup now:              systemctl --user start $UNIT_NAME.service"
        echo "  Watch logs:                    journalctl --user -u $UNIT_NAME -f"
    else
        echo "  No systemd: schedule with cron instead:"
        echo "    17 */6 * * *  cd $REPO_DIR && ./.venv/bin/git-dr-mirror >> ~/.local/state/git-dr-mirror.log 2>&1"
    fi
fi
